name: 'Send Notification'
description: 'Send a notification to the specified webhook'
inputs:
  notification_source:
    description: 'The source sending the event'
    required: true
  webhook_url:
    description: 'The URL of the webhook'
    required: true
  secret_header:
    description: 'The secret header for the webhook'
    required: true
  agent:
    description: 'The agent for the webhook'
    required: true
  message:
    description: 'The message to be sent in the notification'
    required: true
  more_url:
    description: 'The followup URL for more information'
    required: true
  severity:
    description: 'The severity level of the notification'
    required: false
    default: 'critical'

runs:
  using: 'composite'
  steps:
    - name: Send notification
      run: |
        curl -X POST "${{ inputs.webhook_url }}" \
        -H "Content-Type: application/json" \
        -H "X-Custom-Secret: ${{ inputs.secret_header }}" \
        -H "X-Custom-Agent: ${{ inputs.agent }}" \
        -d '{
              "source": "${{ inputs.notification_source }}",
              "severity": "${{ inputs.severity }}",
              "message": "${{ inputs.message }}",
              "url": "${{ inputs.more_url }}"
            }'
      shell: bash
