name: Build and Publish Docker Images

on:
  schedule:
    - cron: '0 9 * * 1'  # Runs every Monday at 9 AM
  workflow_dispatch:  # Allows manual trigger

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Find all Dockerfiles
      id: find_dockerfiles
      run: |
        find . -name 'Dockerfile' | sed 's|/Dockerfile||' > dockerfile_paths.txt

    - name: Build and push Docker images
      run: |
        while IFS= read -r path; do
          image_name="ghcr.io/${{ github.repository_owner }}/$(basename $path | tr '[:upper:]' '[:lower:]')"
          echo "Building and pushing $image_name"
          docker buildx build --push --tag $image_name $path
        done < dockerfile_paths.txt
