name: Cron - Build and Push Docker Images to GHCR

on:
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * 1'  # Runs every Monday at 9 AM

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Find Dockerfiles and build/push images
        id: build_and_push
        run: |
          # Find all Dockerfiles under the managed-containers directory
          dockerfiles=$(find ./managed-containers -name 'Dockerfile')

          # Iterate over each Dockerfile found
          for dockerfile in $dockerfiles; do
            # Get the directory of the Dockerfile
            dockerfile_dir=$(dirname $dockerfile)

            # Generate a unique image name based on the directory name
            base_name="ghcr.io/${{ github.repository_owner }}/$(basename $dockerfile_dir)"
            
            # Convert the image name to lowercase
            image_name=$(echo $base_name | tr '[:upper:]' '[:lower:]')

            # Build the Docker image
            docker build -t $image_name:latest $dockerfile_dir

            # Push the Docker image with the 'latest' tag to GitHub Container Registry
            docker push $image_name:latest

            # Get the image digest
            digest=$(docker inspect --format='{{index .RepoDigests 0}}' $image_name:latest)

            # Get the current date
            date=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

            # URL of the container image
            image_url="https://ghcr.io/${{ github.repository_owner }}/$(basename $dockerfile_dir):latest"

            # Generate YAML file
            echo "---
            image:
              name: $image_name
              digest: $digest
              date: $date
              url: $image_url" > $dockerfile_dir/image-info.yaml

            # Clean up dangling images to free up space
            docker image prune -f
          done


      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          branch: update-image-info-${{ github.run_id }}
          delete-branch: false
          title: Changes by create-pull-request action
          body: Automated changes by [create-pull-request](https://github.com/peter-evans/create-pull-request) GitHub action
          draft: false