name: Build and Publish to GitHub Container Registry

on:
  workflow_dispatch:
  push:
    branches: [main]

env:
  GITHUB_SHA: ${{ github.sha }}
  REGISTRY: ghcr.io/${{ github.repository }}

permissions:
  contents: write
  packages: write

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      images: ${{ steps.filter.outputs.changes }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Filter paths
        uses: dorny/paths-filter@v2.12.0
        id: filter
        with:
          filters: |
            fsdh_images: 'managed-containers/**'

  build-push:
    if: needs.changes.outputs.images != '[]'
    runs-on: ubuntu-latest
    needs: changes
    strategy:
      fail-fast: false
      matrix:
        image: ${{ fromJSON(needs.changes.outputs.images) }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        working-directory: ./managed-containers/${{ matrix.image }}
        run: |
          docker build \
          --build-arg GITHUB_SHA=${{ env.GITHUB_SHA }} \
          -t ${{ env.REGISTRY }}/${{ matrix.image }}:${{ env.GITHUB_SHA }} \
          -t ${{ env.REGISTRY }}/${{ matrix.image }}:latest .

      - name: Push Docker image to GitHub Container Registry
        run: |
          docker push ${{ env.REGISTRY }}/${{ matrix.image }}:${{ env.GITHUB_SHA }}
          docker push ${{ env.REGISTRY }}/${{ matrix.image }}:latest

      - name: Logout from GitHub Container Registry
        run: docker logout ghcr.io
