name: PR Webhook Notification

on:
  pull_request:
    branches:
      - main
    types: [opened]

jobs:
  notify-webhook:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Send webhook notification
      uses: .github/actions/send-notification
      with:
        webhook_url: ${{ secrets.NOTIFICATIONURL }}
        secret_header: ${{ secrets.NOTIFICATIONURL_SECRET_HEADER }}
        agent: ${{ secrets.NOTIFICATIONURL_AGENT }}
        message: 'A new pull request has been created on the main branch.'
        severity: 'info'
