name: PR Merge Notification

on:
  push:
    branches:
      - main

jobs:
  notify-webhook:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Send webhook notification
      uses: ./.github/actions/send-notification
      with:
        webhook_url: ${{ secrets.NOTIFICATIONURL }}
        secret_header: ${{ secrets.NOTIFICATIONURL_SECRET_HEADER }}
        agent: ${{ secrets.NOTIFICATIONURL_AGENT }}
        message: 'A change to the main branch has been successfully merged.'
        severity: 'info'
