name: PR Webhook Notification

on:
  pull_request:
    branches:
      - main
    types: [opened]

jobs:
  notify-webhook:
    runs-on: ubuntu-latest
    steps:
    - name: Send webhook notification
      env:
        WEBHOOK_URL: ${{ secrets.NOTIFICATIONURL }}
        SECRET_HEADER: ${{ secrets.NOTIFICATIONURL_SECRET_HEADER }}
      run: |
        curl -X POST $WEBHOOK_URL \
        -H "Content-Type: application/json" \
        -H "X-Custom-Secret: $SECRET_HEADER" \
        -d '{
              "source": "GitHub Actions",
              "severity": "info",
              "message": "A new pull request has been created on the main branch.",
              "pull_request_url": "${{ github.event.pull_request.html_url }}"
            }'
