name: Security Scan Dockerfiles

# This workflow triggers on workflow dispatch, pull request changes in specified paths, and a scheduled cron job
on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'managed-containers/**/Dockerfile'
      - 'managed-containers/**/image-info.yaml'
  schedule:
    - cron: '0 9 * * MON'

permissions:
  contents: read

jobs:
  build-and-scan:
    runs-on: ubuntu-20.04
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status

    steps:
    # Step 1: Checkout the repository to the GitHub runner
    - name: Checkout repository
      uses: actions/checkout@v4

    # Step 2: Find all image-info.yaml files
    - name: Find image-info.yaml files
      id: find_yaml
      run: |
        echo "::set-output name=image_info_files::$(find ./managed-containers -name 'image-info.yaml')"

    - name: Install Trivy
          run: |
            curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin



    # Step 3: Parse image-info.yaml files and scan Docker images
    - name: Scan Docker images
      if: steps.find_yaml.outputs.image_info_files != ''
      run: |
        for file in ${{ steps.find_yaml.outputs.image_info_files }}
        do
          url=$(yq e '.image.url' "$file")
          if [ -n "$url" ]; then
            echo "Scanning $url..."
            trivy image --severity CRITICAL,HIGH --format sarif --output trivy-results-$(basename $file .yaml).sarif $url
          fi
        done

    # Step 4: Upload Trivy scan results to GitHub Security tab
    - name: Upload Trivy scan results to GitHub Security tab
      uses: actions/upload-artifact@v2
      with:
        name: Trivy Scan Results
        path: ./*.sarif

    # Optional: Additional steps if needed, such as notifying stakeholders
