name: Build and Scan Docker Image

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'managed-containers/shiny-app/**'
  schedule:
    - cron: '0 9 * * MON'

jobs:
  build-and-scan:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Build Docker image
      run: |
        docker build -t my-app:latest ./managed-containers/shiny-app

    - name: Run Trivy vulnerability scanner
      id: trivy-scan
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'my-app:latest'
        format: 'sarif'
        output: 'trivy-results.sarif'

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: 'trivy-results.sarif'

    - name: Send SRE webhook notification
      if: failure()
      env:
        WEBHOOK_URL: ${{ secrets.NOTIFICATIONURL }}
        SECRET_HEADER: ${{ secrets.NOTIFICATIONURL_SECRET_HEADER }}
        AGENT: ${{ secrets.NOTIFICATIONURL_AGENT }}
      run: |
        curl -X POST $WEBHOOK_URL \
        -H "Content-Type: application/json" \
        -H "X-Custom-Secret: $SECRET_HEADER" \
        -H "X-Custom-Agent: $AGENT" \
        -d '{
              "source": "GitHub Actions",
              "severity": "critical",
              "message": "Trivy scan detected vulnerabilities in the Docker image.",
              "details": "${{ steps.trivy-scan.outputs.result }}"
            }'
