name: Cron - Security Scan Container Registry

# This workflow triggers on workflow dispatch, pull request changes in specified paths, and a scheduled cron job
on:
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * MON'

permissions:
  contents: read
  security-events: write

jobs:
  build-and-scan:
    runs-on: ubuntu-20.04

    steps:
    # Step 1: Checkout the repository to the GitHub runner
    - name: Checkout repository
      uses: actions/checkout@v4

    # Step 2: Install Trivy
    - name: Install Trivy
      run: |
        echo "Installing Trivy..."
        curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin
        mkdir -p trivy-results

    # Step 3: Find all image-info.yaml files and scan Docker images
    - name: Find and Scan Docker images
      id: find_and_scan
      run: |
        echo "Finding image-info.yaml files..."
        image_info_files=$(find ./managed-containers -name 'image-info.yaml')

        if [ -n "$image_info_files" ]; then
          echo "Parsing image-info.yaml files and scanning Docker images..."
          
          for file in $image_info_files
          do
            url=$(yq e '.image.url' "$file")
            if [ -n "$url" ]; then
              # Extract the container name and convert to lowercase
              container_name=$(echo ${url##*/} | tr '[:upper:]' '[:lower:]')
              echo "Scanning $container_name..."
              trivy image --severity CRITICAL,HIGH --format sarif --output trivy-results/${container_name}.sarif $url
            fi
          done
        else
          echo "No image-info.yaml files found."
        fi

    # Step 4: Upload Trivy scan results as artifacts
    #- name: Upload Trivy scan results as artifacts
    #  uses: actions/upload-artifact@v4
    #  with:
    #    name: Trivy Scan Results
    #    path: trivy-results/*.sarif

    # Step 5: Upload SARIF file to GitHub Code Scanning
    - name: Upload SARIF to GitHub Code Scanning
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: trivy-results/
